# Dockerfile.fastapi

FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt \
    && pip install fastapi uvicorn psycopg2-binary pydantic

EXPOSE 8000

CMD ["uvicorn", "run_api:app", "--host", "0.0.0.0", "--port", "8000"]