version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333'
    volumes:
      - qdrant_storage:/qdrant/storage
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: 'neo4j/neo4j'
    ports:
      - '7474:7474'
      - '7687:7687'
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/srv/app
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - qdrant
      - neo4j
volumes:
  qdrant_storage: